### ISSUE TITLE
CV2 doesn't use second MIDI note on the according setting

### ISSUE THREAD

**Issue by djraw** [albertfc/antz#3]
Hi Albert, when the dip switch is set to use CV2 as second note, currently it just outputs the same voltage as CV1.

According to Ants' manual it was supposed to alter the voltage based on the second midi note that is received.

**Comment by albertfc** [comment]
Hi, 

Just now, we have released a new version of the firmware implementing legato and fixing some minor issues. Maybe you can give it a try and see if it fixes your problems.
There is also a precompiled version of the firmware (src/antz.hex), in case you have any troubles compiling it yourself.

**Comment by djraw** [comment]
The CV2 didn't work for me because of my weird MIDI setup. The latest firmware works like a charm and has very cool new features that make playing Ants even better.
